### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by ghost** [tegansnyder/JQuery-Mobile-Slide-Menu#1] opened 2012-05-18 13:19 UTC
Hey Tegan,

The container now resizes correctly, tested on my iphone too :)

There's one other small issue with the menu, check out http://neilberry.com/app2/

I've added another page to your app as an example.  Click on Activity and this page will open correctly.

However, clicking on the menu icon again doesn't work, any ideas how we can get it working?

Thanks
Neil

**Comment by ghost** [comment] 2012-05-18 13:19
Let me know if you want me to test anything ;)

**Comment by tegansnyder** [comment] 2012-05-18 13:40
This is now fixed. I updated the click handler, added a event for stopping propagation.

``` javascript
$(document).on("click", ":jqmData(slidemenu)", function(event) {
        event.stopImmediatePropagation();
        slidemenu(sm);
});
```

**Closed as completed by tegansnyder** 2012-05-18 13:40 UTC

**Comment by linuxonrails** [comment] 2012-05-21 16:17
The problem is not fixed :-(
